# Generated by Django 4.0.2 on 2022-06-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer')], default='employee', max_length=10),
        ),
    ]
