# Generated by Django 4.0.2 on 2022-06-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_employeeprofile_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='job_title',
            new_name='job_title1',
        ),
    ]
