# Generated by Django 4.0.2 on 2022-06-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_job_title_employeeprofile_job_title1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='job_title1',
            new_name='job_title',
        ),
    ]
